/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package configurafacil.Presentation;

import configurafacil.Business.Componente;
import configurafacil.Business.ConfiguraFacil;

/**
 *
 * @author utilizador
 */
public class Estofos extends javax.swing.JDialog {
    private ConfiguraFacil configura;
    private String estofo = "";
    private Configuracao parent;
    private EscolherCarro parent2;
    
    /**
     * Creates new form Estofos
     */
    public Estofos(javax.swing.JDialog parent, javax.swing.JDialog parent2, boolean modal, ConfiguraFacil c) {
       super(parent, modal);
       initComponents();
       this.configura = c;
       this.parent = (Configuracao) parent;
       this.parent2 = (EscolherCarro) parent2;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Estofo1 = new javax.swing.JRadioButton();
        Estofo2 = new javax.swing.JRadioButton();
        Estofo3 = new javax.swing.JRadioButton();
        Estofo4 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        buttonGroup1.add(Estofo1);
        Estofo1.setText("Couro comfort carvão");
        Estofo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Estofo1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(Estofo2);
        Estofo2.setText("Couro comfort âmbar");
        Estofo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Estofo2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(Estofo3);
        Estofo3.setText("Couro comfort maroon brown ");
        Estofo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Estofo3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(Estofo4);
        Estofo4.setText("Couro comfort blond");
        Estofo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Estofo4ActionPerformed(evt);
            }
        });

        jButton1.setText("Guardar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Estofos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Estofo2)
                            .addComponent(Estofo3)
                            .addComponent(Estofo4)
                            .addComponent(Estofo1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel1)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1)
                .addGap(18, 18, 18)
                .addComponent(Estofo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Estofo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Estofo3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Estofo4)
                .addGap(31, 31, 31)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Estofo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Estofo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Estofo1ActionPerformed

    private void Estofo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Estofo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Estofo2ActionPerformed

    private void Estofo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Estofo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Estofo3ActionPerformed

    private void Estofo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Estofo4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Estofo4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        if(Estofo1.isSelected()) this.estofo = "Couro comfort carvão";
        if(Estofo2.isSelected()) this.estofo = "Couro comfort âmbar";
        if(Estofo3.isSelected()) this.estofo = "Couro comfort maroon brown";
        if(Estofo4.isSelected()) this.estofo = "Couro comfort blond";
        if(this.estofo.equals("")){
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor escolha um estofo","Estofo não selecionado", 0);
        }
        else {
            Componente comp = configura.getStand().getComponente(this.estofo);
            Componente c = this.parent.verificaTipo(this.parent2.encomenda, "Estofo");
            if(c != null){
                this.parent2.encomenda.removeDaConfiguracao(c);
            }
            this.parent2.encomenda.addToConfiguracao(comp);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Estofo1;
    private javax.swing.JRadioButton Estofo2;
    private javax.swing.JRadioButton Estofo3;
    private javax.swing.JRadioButton Estofo4;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
