/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package configurafacil.Presentation;

import configurafacil.Business.Componente;
import configurafacil.Business.ConfiguraFacil;

/**
 *
 * @author utilizador
 */
public class Jantes extends javax.swing.JDialog {
    private ConfiguraFacil configura;
    private String jante = "";
    private EscolherCarro parent2;
    
    /**
     * Creates new form Jantes
     */
    public Jantes(javax.swing.JDialog parent, javax.swing.JDialog parent2, boolean modal, ConfiguraFacil c) {
       super(parent, modal);
       initComponents();
       this.configura = c;
       this.parent2 = (EscolherCarro) parent2;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Jante1 = new javax.swing.JRadioButton();
        Jante2 = new javax.swing.JRadioButton();
        Jante3 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        buttonGroup1.add(Jante1);
        Jante1.setText("Jantes em liga leve 17''");
        Jante1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jante1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(Jante2);
        Jante2.setText("Jantes em liga leve 18'' 245/45  R18");
        Jante2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jante2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(Jante3);
        Jante3.setText("Jantes em liga leve 19'' 255/40 R19");
        Jante3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jante3ActionPerformed(evt);
            }
        });

        jButton1.setText("Guardar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Jantes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Jante3)
                            .addComponent(Jante2)
                            .addComponent(Jante1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel1)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Jante1)
                .addGap(18, 18, 18)
                .addComponent(Jante2)
                .addGap(18, 18, 18)
                .addComponent(Jante3)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Jante1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jante1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jante1ActionPerformed

    private void Jante2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jante2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jante2ActionPerformed

    private void Jante3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jante3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jante3ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        if(Jante1.isSelected()) this.jante = "Jantes em liga leve 17''";
        if(Jante2.isSelected()) this.jante = "Jantes em liga leve 18'' 245/45  R18";
        if(Jante3.isSelected()) this.jante = "Jantes em liga leve 19'' 255/40 R19";
        if(this.jante.equals("")){
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor escolha uma jantes","Jantes não selecionado", 0);
        }
        else {
            Componente comp = configura.getStand().getComponente(this.jante);
            this.parent2.encomenda.addToConfiguracao(comp);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Jante1;
    private javax.swing.JRadioButton Jante2;
    private javax.swing.JRadioButton Jante3;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
